[workspace]
resolver = "2"
members = [
    "bin/server",
    "packages/domain",
    "packages/engine",
    "packages/gateway",
    "packages/cache",
    "packages/workers",
    "packages/risk",
    "packages/queue",
]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
